"""Deterministic, plan-driven report generator (STAGE3_PLAN §0.3).

`generate(records, meta) -> markdown` emits numbers + tables + NEUTRAL labels only — no
interpretation, no hardcoded operator/arm/model literals, no `date.today()`. The date comes from
the manifest. This is the ONLY place a sweep number is authored; the human `_analysis.md` narrative
cites these numbers and may not introduce one that is not here (checked by check_analysis_numbers.py).

`generate_from_cases(root, name)` is the results/ path; rebuild_tables.py calls `generate(records,
meta)` directly with release-sourced records so the same bytes come out with no registry access.
"""
from __future__ import annotations

import collections
import json
from pathlib import Path

import yaml

from harness import sweep_stats as ss
from harness.anchors import normalize_anchor


def _f(x, nd=3):
    return "n/a" if x is None else f"{x:.{nd}f}"


def _ci(c, nd=3):
    if not c or c.get("point") is None:
        return "n/a"
    return f"{c['point']:.{nd}f} [{_f(c.get('lo'), nd)}, {_f(c.get('hi'), nd)}]"


def generate(records: list[dict], meta: dict) -> str:
    """Build the deterministic markdown from attached records + report metadata.

    meta: {name, date, model, plan_arms, n_cells, excluded}. All content is derived from the
    records; meta only supplies provenance strings (never numbers computed from the data).
    """
    s = ss.compute_all(records)
    name = meta["name"]
    # Evidence scorer version actually present on this sweep's records (guard-checked against the
    # records/release by scripts/check_scorer_versions.py — a provenance fact about the instrument).
    _sv = collections.Counter((r.get("scores") or {}).get("evidence", {}).get("scorer_version")
                              for r in records if isinstance((r.get("scores") or {}).get("evidence"), dict))
    _sv.pop(None, None)
    scorer_version = _sv.most_common(1)[0][0] if _sv else "unknown"
    L: list[str] = []
    L += [f"# Sweep {name} — generated report", ""]
    L += ["> Machine-generated by `harness/report_gen.py` from records — do NOT hand-edit. "
          "Regenerate with `make report NAME=%s`. Interpretation lives in the `_analysis.md` narrative." % name, ""]
    L += [f"- date (from manifest): {meta.get('date','?')}",
          f"- model: {meta.get('model','?')}",
          f"- n_trials: {s['n_trials']}  ·  n_cases: {s['n_cases']}"
          + (f"  ·  n_cells(plan): {meta['n_cells']}" if meta.get('n_cells') is not None else ""),
          f"- faulty operators: {', '.join(s['operators_faulty']) or '(none)'}",
          f"- control operators: {', '.join(s['operators_control']) or '(none)'}",
          f"- arms present: {', '.join(s['arms'])}"
          + (f"  ·  arms (plan): {', '.join(meta['plan_arms'])}" if meta.get('plan_arms') else ""),
          f"- agents: {', '.join(s['agents'])}",
          f"- evidence scorer: {scorer_version}",
          f"- excluded: trusted={meta.get('excluded',{}).get('trusted',0)}, "
          f"superseded={meta.get('excluded',{}).get('superseded',0)}",
          f"- method: {s['method']}", ""]

    # Detection by operator × arm
    arms = s["arms"]
    L += ["## Detection by operator × arm (point [95% case-clustered CI])", "",
          "| operator | " + " | ".join(arms) + " |",
          "|" + "---|" * (len(arms) + 1)]
    dba = s["detection_by_operator_arm"]
    for op in s["operators_faulty"]:
        row = [op] + [_ci(dba.get(op, {}).get(arm)) for arm in arms]
        L.append("| " + " | ".join(row) + " |")
    L += [""]

    # H1 anchor-off pooled gap
    g = s["h1_anchor_gap_pooled"]
    L += ["## H1 — anchor-off detection gap (negative − positive symptom), pooled", "",
          f"- gap: {_ci(g)}  (negative {_f(g.get('neg_rate'))} on {g.get('n_cases_neg')} cases − "
          f"positive {_f(g.get('pos_rate'))} on {g.get('n_cases_pos')} cases)",
          f"- positive-symptom operators: {', '.join(g.get('positive_ops') or []) or '(none)'}",
          f"- negative-symptom operators: {', '.join(g.get('negative_ops') or []) or '(none)'}",
          f"- nearest-σ matched mean paired gap: {_f(ss.h1_matched_sigma(records).get('mean_paired_gap'))} "
          "_(supplementary heuristic; does NOT resolve the operator-identity confound. The pairing "
          "uses each case's current `hidden_sigma_distance`, so it moves when a case is rebuilt — "
          "e.g. lr_warmup's bimodal rebuild changed which negative cases pair to each leakage case.)_", ""]

    # Ratio of the off→rule gap closed by the mid arm (the pre-registered, previously-uncomputed stat)
    r = s["ratio_gap_closed"]
    L += ["## Fraction of the off→rule detection gap closed by the numbers/stats arm", ""]
    if not r.get("available"):
        L += [f"_not available: {r.get('reason')}_", ""]
    else:
        L += [f"Method: {r['method']}. Arms: {r['low_arm']}→{r['mid_arm']}→{r['high_arm']}.", "",
              "| operator | detect off | detect numbers | detect rule | gap | fraction closed by numbers (95% CI) |",
              "|---|---|---|---|---|---|"]
        for op in s["operators_faulty"]:
            d = r["operators"].get(op)
            if not d:
                continue
            fc = "degenerate (no gap)" if d["degenerate_gap"] else _ci(d["fraction_closed_by_mid"])
            L.append(f"| {op} | {_f(d.get('detect_'+r['low_arm']))} | {_f(d.get('detect_'+r['mid_arm']))} | "
                     f"{_f(d.get('detect_'+r['high_arm']))} | {_f(d.get('gap_low_high'))} | {fc} |")
        L += [""]

    # Control FPR — per arm + numbers−rule difference
    c = s["control_fpr"]
    L += ["## Control detection false-positive rate (per arm, case-clustered)", ""]
    if not c.get("available"):
        L += [f"_not available: {c.get('reason')}_", ""]
    else:
        L += ["| arm | FP rate (95% CI) | n_fp / n_trials | unique FP cases / control cases |",
              "|---|---|---|---|"]
        for arm in sorted(c["per_arm"]):
            a = c["per_arm"][arm]
            L.append(f"| {arm} | {_ci(a)} | {a['n_fp']}/{a['n_trials']} | {len(a['fp_cases'])}/{a['n_cases']} |")
        if "numbers_minus_rule" in c:
            L += ["", f"- numbers − rule FP difference: {_ci(c['numbers_minus_rule'])}"]
        L += [""]

    # ReAct − static
    h6 = s["h6_react_minus_static"]
    L += ["## ReAct − static evidence F1 (faulty operators, pooled)", ""]
    L += ([f"- {_ci(h6)} (n_cases={h6.get('n_cases')})", ""] if h6.get("available")
          else [f"_not available: {h6.get('reason')}_", ""])

    # Recovery endpoints
    L += ["## Recovery — strict vs semantic, with id-gap CIs", "",
          "| operator | n_trials | n_cases | identification | strict recovery | semantic recovery | id − strict (95% CI) | id − semantic (95% CI) |",
          "|---|---|---|---|---|---|---|---|"]
    for op, e in s["recovery_endpoints"].items():
        L.append(f"| {op} | {e['n_trials']} | {e['n_cases']} | {_f(e['identification'],4)} | "
                 f"{_f(e['strict_recovery'],4)} | {_f(e['semantic_recovery'],4)} | "
                 f"{_ci(e['id_minus_strict'])} | {_ci(e['id_minus_semantic'])} |")
    L += [""]
    return "\n".join(L) + "\n"


def _meta_from_dir(d: Path, name: str) -> dict:
    """Provenance meta (date/model/plan-arms/n_cells) from a dir holding <name>_plan/manifest.yaml.

    Works for both `sweeps/` (results path) and a release dir (reviewer path) — same files, so the
    meta strings are identical and the two reports are byte-identical."""
    plan_p, man_p = d / f"{name}_plan.yaml", d / f"{name}_manifest.yaml"
    plan = yaml.safe_load(plan_p.read_text()) if plan_p.exists() else {}
    man = yaml.safe_load(man_p.read_text()) if man_p.exists() else {}
    header = plan.get("header", {})
    date = (man.get("timestamp_utc") or "").split("T")[0] or header.get("created_utc", "").split("T")[0]
    arms = (header.get("factor_levels", {}) or {}).get("anchors")
    plan_arms = sorted({normalize_anchor(a) for a in arms}) if arms else None
    return {"name": name, "date": date, "model": header.get("model"),
            "plan_arms": plan_arms, "n_cells": header.get("n_cells")}


def generate_from_cases(root: Path, name: str, excluded: dict | None = None) -> str:
    records = ss.load_from_cases(root, name)
    meta = _meta_from_dir(root / "sweeps", name)
    meta["excluded"] = excluded or {"trusted": 0, "superseded": 0}
    return generate(records, meta)


def generate_from_release(release_dir: Path, name: str) -> str:
    """Reviewer path: regenerate the report from a sanitized release only (no cases/, no registry)."""
    release_dir = Path(release_dir)
    records = ss.load_from_release(release_dir)
    meta = _meta_from_dir(release_dir, name)
    rm = release_dir / "release_meta.json"
    meta["excluded"] = (json.loads(rm.read_text()).get("excluded")
                        if rm.exists() else {"trusted": 0, "superseded": 0})
    return generate(records, meta)
