"""Deterministic, plan-driven report generator (STAGE3_PLAN §0.3).

`generate(records, meta) -> markdown` emits numbers + tables + NEUTRAL labels only — no
interpretation, no hardcoded operator/arm/model literals, no `date.today()`. The date comes from
the manifest. This is the ONLY place a sweep number is authored; the human `_analysis.md` narrative
cites these numbers and may not introduce one that is not here (checked by check_analysis_numbers.py).

`generate_from_cases(root, name)` is the results/ path; rebuild_tables.py calls `generate(records,
meta)` directly with release-sourced records so the same bytes come out with no registry access.
"""
from __future__ import annotations

import collections
import json
from pathlib import Path

import yaml

from harness import sweep_stats as ss
from harness.anchors import normalize_anchor


def _f(x, nd=3):
    return "n/a" if x is None else f"{x:.{nd}f}"


def _ci(c, nd=3):
    if not c or c.get("point") is None:
        return "n/a"
    return f"{c['point']:.{nd}f} [{_f(c.get('lo'), nd)}, {_f(c.get('hi'), nd)}]"


def generate(records: list[dict], meta: dict) -> str:
    """Build the deterministic markdown from attached records + report metadata.

    meta: {name, date, model, plan_arms, n_cells, excluded}. All content is derived from the
    records; meta only supplies provenance strings (never numbers computed from the data).
    """
    s = ss.compute_all(records)
    name = meta["name"]
    # Evidence scorer version actually present on this sweep's records (guard-checked against the
    # records/release by scripts/check_scorer_versions.py — a provenance fact about the instrument).
    _sv = collections.Counter((r.get("scores") or {}).get("evidence", {}).get("scorer_version")
                              for r in records if isinstance((r.get("scores") or {}).get("evidence"), dict))
    _sv.pop(None, None)
    scorer_version = _sv.most_common(1)[0][0] if _sv else "unknown"
    L: list[str] = []
    L += [f"# Sweep {name} — generated report", ""]
    L += ["> Machine-generated by `harness/report_gen.py` from records — do NOT hand-edit. "
          "Regenerate with `make report NAME=%s`. Interpretation lives in the `_analysis.md` narrative." % name, ""]
    L += [f"- date (from manifest): {meta.get('date','?')}",
          f"- model: {meta.get('model','?')}",
          f"- n_trials: {s['n_trials']}  ·  n_cases: {s['n_cases']}"
          + (f"  ·  n_cells(plan): {meta['n_cells']}" if meta.get('n_cells') is not None else ""),
          f"- faulty operators: {', '.join(s['operators_faulty']) or '(none)'}",
          f"- control operators: {', '.join(s['operators_control']) or '(none)'}",
          f"- arms present: {', '.join(s['arms'])}"
          + (f"  ·  arms (plan): {', '.join(meta['plan_arms'])}" if meta.get('plan_arms') else ""),
          f"- agents: {', '.join(s['agents'])}",
          f"- evidence scorer: {scorer_version}",
          f"- excluded: trusted={meta.get('excluded',{}).get('trusted',0)}, "
          f"superseded={meta.get('excluded',{}).get('superseded',0)}",
          f"- method: {s['method']}", ""]

    providers = ss.providers_present(records)
    if len(providers) > 1:
        # H7: split every table by provider with pooled alongside; list both models.
        L += [f"- providers: {', '.join(providers)}",
              f"- models: {', '.join(meta.get('models') or [])}", ""]
        L += ["## Pooled — all providers", ""] + _metric_body(s, records, meta)
        for p in providers:
            sub = [r for r in records if r.get("_provider") == p]
            L += [f"## Provider: {p}", ""] + _metric_body(ss.compute_all(sub), sub, meta)
    else:
        L += _metric_body(s, records, meta)
    # H8 renders only when the neutral+descriptive pair is present (self-guarded),
    # so frozen single-variant sweeps are byte-identical.
    L += _h8_tables(s)
    return "\n".join(L) + "\n"


def _h8_tables(s: dict) -> list:
    """H8 primary (neutral − descriptive identification Δ, per arm × provider, judged
    vs pre-registered thresholds) + secondary (detection/recovery per variant)."""
    h = s.get("h8_identification_contrast", {})
    if not h.get("available"):
        return []
    B = ["## H8 — neutral − descriptive identification (Δ), per arm × provider", "",
         f"Δ = neutral − descriptive identification. Pre-registered equivalence test on the "
         f"case-clustered 95% CI: confirming iff the WHOLE CI is inside ±{h['confirming_bound']} "
         f"(lo > −{h['confirming_bound']} and hi < +{h['confirming_bound']}); refuting iff Δ < "
         f"−{h['refuting_bound']} and the CI excludes 0 (hi < 0); otherwise inconclusive.", "",
         "| provider | arm | neutral id | descriptive id | Δ (95% CI) | n cases neut/desc | verdict |",
         "|---|---|---|---|---|---|---|"]
    for row in h["rows"]:
        B.append(f"| {row['provider']} | {row['arm']} | {_f(row.get('neutral_id'))} | "
                 f"{_f(row.get('descriptive_id'))} | {_ci(row)} | "
                 f"{row['n_cases_neutral']}/{row['n_cases_descriptive']} | {row['verdict']} |")
    B += [""]
    sec = s.get("h8_secondary_detection_recovery", {})
    if sec.get("available"):
        B += ["### H8 secondary — detection + semantic recovery per variant × arm × provider "
              "(pre-registered: expected UNCHANGED between variants)", "",
              "| provider | variant | arm | detection | recovery | n_trials | n_cases |",
              "|---|---|---|---|---|---|---|"]
        for row in sec["rows"]:
            B.append(f"| {row['provider']} | {row['variant']} | {row['arm']} | "
                     f"{_f(row.get('detection'))} | {_f(row.get('recovery'))} | "
                     f"{row['n_trials']} | {row['n_cases']} |")
        B += [""]
    return B


def _metric_body(s: dict, records: list, meta: dict) -> list:
    """The standard metric tables for one facet of records (all records, or one
    provider's). Extracted verbatim so the single-provider path stays byte-identical."""
    B: list = []
    # Detection by operator × arm
    arms = s["arms"]
    B += ["## Detection by operator × arm (point [95% case-clustered CI])", "",
          "| operator | " + " | ".join(arms) + " |",
          "|" + "---|" * (len(arms) + 1)]
    dba = s["detection_by_operator_arm"]
    for op in s["operators_faulty"]:
        row = [op] + [_ci(dba.get(op, {}).get(arm)) for arm in arms]
        B.append("| " + " | ".join(row) + " |")
    B += [""]

    # H1 anchor-off pooled gap
    g = s["h1_anchor_gap_pooled"]
    B += ["## H1 — anchor-off detection gap (negative − positive symptom), pooled", "",
          f"- gap: {_ci(g)}  (negative {_f(g.get('neg_rate'))} on {g.get('n_cases_neg')} cases − "
          f"positive {_f(g.get('pos_rate'))} on {g.get('n_cases_pos')} cases)",
          f"- positive-symptom operators: {', '.join(g.get('positive_ops') or []) or '(none)'}",
          f"- negative-symptom operators: {', '.join(g.get('negative_ops') or []) or '(none)'}",
          f"- nearest-σ matched mean paired gap: {_f(ss.h1_matched_sigma(records).get('mean_paired_gap'))} "
          "_(supplementary heuristic; does NOT resolve the operator-identity confound. The pairing "
          "uses each case's current `hidden_sigma_distance`, so it moves when a case is rebuilt — "
          "e.g. lr_warmup's bimodal rebuild changed which negative cases pair to each leakage case.)_", ""]

    # Ratio of the off→rule gap closed by the mid arm (the pre-registered, previously-uncomputed stat)
    r = s["ratio_gap_closed"]
    B += ["## Fraction of the off→rule detection gap closed by the numbers/stats arm", ""]
    if not r.get("available"):
        B += [f"_not available: {r.get('reason')}_", ""]
    else:
        B += [f"Method: {r['method']}. Arms: {r['low_arm']}→{r['mid_arm']}→{r['high_arm']}.", "",
              "| operator | detect off | detect numbers | detect rule | gap | fraction closed by numbers (95% CI) |",
              "|---|---|---|---|---|---|"]
        for op in s["operators_faulty"]:
            d = r["operators"].get(op)
            if not d:
                continue
            fc = "degenerate (no gap)" if d["degenerate_gap"] else _ci(d["fraction_closed_by_mid"])
            B.append(f"| {op} | {_f(d.get('detect_'+r['low_arm']))} | {_f(d.get('detect_'+r['mid_arm']))} | "
                     f"{_f(d.get('detect_'+r['high_arm']))} | {_f(d.get('gap_low_high'))} | {fc} |")
        B += [""]

    # Control FPR — per arm + numbers−rule difference
    c = s["control_fpr"]
    B += ["## Control detection false-positive rate (per arm, case-clustered)", ""]
    if not c.get("available"):
        B += [f"_not available: {c.get('reason')}_", ""]
    else:
        B += ["| arm | FP rate (95% CI) | n_fp / n_trials | unique FP cases / control cases |",
              "|---|---|---|---|"]
        for arm in sorted(c["per_arm"]):
            a = c["per_arm"][arm]
            B.append(f"| {arm} | {_ci(a)} | {a['n_fp']}/{a['n_trials']} | {len(a['fp_cases'])}/{a['n_cases']} |")
        # §5.1: stratified breakdown (in-band vs out-of-band) when controls carry
        # band labels. Never present the pooled rate alone once we have this.
        def _band_table(title, breakdown):
            rows = ["", title, "",
                    "| arm | band | FP rate (95% CI) | n_fp / n_trials | unique FP cases / control cases |",
                    "|---|---|---|---|---|"]
            for arm in sorted(breakdown):
                for band in ("in_band", "out_of_band"):
                    b = breakdown[arm][band]
                    if not b.get("available"):
                        rows.append(f"| {arm} | {band} | _no controls in stratum_ | 0/0 | 0/0 |")
                    else:
                        rows.append(f"| {arm} | {band} | {_ci(b)} | {b['n_fp']}/{b['n_trials']} | "
                                    f"{len(b['fp_cases'])}/{b['n_cases']} |")
            return rows
        if c.get("stratified"):
            # PRIMARY: visible band position — the key by mechanism (a control false
            # positive is a visible-metric event: the agent reads the visible metric,
            # compares to its band, and flags).
            B += _band_table("### Stratified by VISIBLE band position (§5.1 — the key, by mechanism)",
                             c["by_band"])
            # ALONGSIDE: hidden band position as a case-quality label (the agent never
            # sees it; no causal path to the false positive being measured).
            if c.get("by_band_hidden"):
                B += _band_table(
                    "### Stratified by HIDDEN band position "
                    "(case-quality label, reported alongside — not the key; the agent never sees it)",
                    c["by_band_hidden"])
        if "numbers_minus_rule" in c:
            B += ["", f"- numbers − rule FP difference: {_ci(c['numbers_minus_rule'])}"]
        B += [""]

    # ReAct − static
    h6 = s["h6_react_minus_static"]
    B += ["## ReAct − static evidence F1 (faulty operators, pooled)", ""]
    B += ([f"- {_ci(h6)} (n_cases={h6.get('n_cases')})", ""] if h6.get("available")
          else [f"_not available: {h6.get('reason')}_", ""])

    # Recovery endpoints
    B += ["## Recovery — strict vs semantic, with id-gap CIs", "",
          "| operator | n_trials | n_cases | identification | strict recovery | semantic recovery | id − strict (95% CI) | id − semantic (95% CI) |",
          "|---|---|---|---|---|---|---|---|"]
    for op, e in s["recovery_endpoints"].items():
        B.append(f"| {op} | {e['n_trials']} | {e['n_cases']} | {_f(e['identification'],4)} | "
                 f"{_f(e['strict_recovery'],4)} | {_f(e['semantic_recovery'],4)} | "
                 f"{_ci(e['id_minus_strict'])} | {_ci(e['id_minus_semantic'])} |")
    B += [""]
    return B


def _meta_from_dir(d: Path, name: str) -> dict:
    """Provenance meta (date/model/plan-arms/n_cells) from a dir holding <name>_plan/manifest.yaml.

    Works for both `sweeps/` (results path) and a release dir (reviewer path) — same files, so the
    meta strings are identical and the two reports are byte-identical."""
    plan_p, man_p = d / f"{name}_plan.yaml", d / f"{name}_manifest.yaml"
    plan = yaml.safe_load(plan_p.read_text()) if plan_p.exists() else {}
    man = yaml.safe_load(man_p.read_text()) if man_p.exists() else {}
    header = plan.get("header", {})
    date = (man.get("timestamp_utc") or "").split("T")[0] or header.get("created_utc", "").split("T")[0]
    arms = (header.get("factor_levels", {}) or {}).get("anchors")
    plan_arms = sorted({normalize_anchor(a) for a in arms}) if arms else None
    models = (header.get("factor_levels", {}) or {}).get("models")
    return {"name": name, "date": date, "model": header.get("model"),
            "models": models, "plan_arms": plan_arms, "n_cells": header.get("n_cells")}


def generate_from_cases(root: Path, name: str, excluded: dict | None = None) -> str:
    records = ss.load_from_cases(root, name)
    meta = _meta_from_dir(root / "sweeps", name)
    meta["excluded"] = excluded or {"trusted": 0, "superseded": 0}
    return generate(records, meta)


def generate_from_release(release_dir: Path, name: str) -> str:
    """Reviewer path: regenerate the report from a sanitized release only (no cases/, no registry)."""
    release_dir = Path(release_dir)
    records = ss.load_from_release(release_dir)
    meta = _meta_from_dir(release_dir, name)
    rm = release_dir / "release_meta.json"
    meta["excluded"] = (json.loads(rm.read_text()).get("excluded")
                        if rm.exists() else {"trusted": 0, "superseded": 0})
    return generate(records, meta)
