#!/usr/bin/env python3
"""B2+ report — the UPPER BOUND "config-diff with perfect knob semantics" (STAGE4_PLAN 4.0.6).

B2+ identifies a changed knob through `harness/b2plus_map.yaml`, the ANSWER KEY (exactly the knobs our
operators inject). On our own faulty operators its identification is perfect by construction, so that
row is reported only to show the bound, never as validation. What IS informative:

  * FALLBACK — on knobs NOT in the map (the benign-control knobs, any future operator's knob), how
    often B2+ falls back to B2's bare leaf name;
  * FALSE POSITIVES — on healthy and benign controls, how often a config diff flags a fault at all,
    and, when a benign change touches a fault knob (e.g. a normal-range learning-rate change), how
    often B2+ names that fault's concept.

Runs over already-built cases (no building): scoring reads hidden cards, so run it in the canonical
container (`make docker-b2plus-report`; CI build-and-certify runs it on the freshly built cases).
"""
from __future__ import annotations

import argparse
import glob
import hashlib
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from harness.baselines import B2PLUS_MAP_PATH, load_b2plus_map, score_baseline  # noqa: E402

OUT = ROOT / "docs" / "audits" / "b2plus_report.md"


def _operator(case_dir: Path) -> str:
    # evaluator-side (container): the operator id labels the row; never shown to a baseline
    return (yaml.safe_load((case_dir / "hidden" / "card.hidden.yaml").read_text()) or {})["operator_id"]


def run(case_dirs: list[Path], root: Path) -> str:
    rows = defaultdict(lambda: defaultdict(int))
    classes = defaultdict(set)
    for cd in case_dirs:
        op = _operator(cd)
        sub, sc = score_baseline(cd, "b2plus", project_root=root)
        r = rows[op]
        r["n"] += 1
        fired = bool(sub["diagnosis"]["detected"])
        r["fired"] += fired
        if fired:
            r["hit"] += bool(sub.get("b2plus_map_hit"))
            r["fallback"] += not sub.get("b2plus_map_hit")
            classes[op].add(sub["diagnosis"]["operator_class"])
        r["det_correct"] += bool(sc["detection"]["correct"])
        r["id_correct"] += bool(sc["identification"]["correct"])
    map_sha = hashlib.sha256(B2PLUS_MAP_PATH.read_bytes()).hexdigest()
    version = (yaml.safe_load(B2PLUS_MAP_PATH.read_text()) or {}).get("version")
    L = ["# B2+ — UPPER BOUND: config-diff with perfect knob semantics", "",
         "> Generated by `scripts/b2plus_report.py` in the canonical container; do NOT hand-edit. "
         "B2+ maps a changed knob through the ANSWER KEY (`harness/b2plus_map.yaml` v%s, sha256 `%s`, "
         "%d knobs = exactly the knobs our operators inject). On our faulty operators its "
         "identification is perfect **by construction** — those rows show the bound and validate "
         "nothing. It is never a baseline an LLM is compared against to claim value." % (
             version, map_sha, len(load_b2plus_map())), "",
         "| operator | cases | B2+ fires | answer-key hit | FALLBACK (leaf name) | detection correct | "
         "identification correct | class(es) named |", "|---|---|---|---|---|---|---|---|"]
    for op in sorted(rows):
        r = rows[op]
        L.append(f"| {op} | {r['n']} | {r['fired']}/{r['n']} | {r['hit']}/{r['fired']} | "
                 f"{r['fallback']}/{r['fired']} | {r['det_correct']}/{r['n']} | {r['id_correct']}/{r['n']} | "
                 f"{', '.join(sorted(classes[op])) or '—'} |")
    ctrl = [op for op in rows if op.startswith("control.")]
    fired = sum(rows[o]["fired"] for o in ctrl)
    n = sum(rows[o]["n"] for o in ctrl)
    fb = sum(rows[o]["fallback"] for o in ctrl)
    L += ["", f"**Controls (healthy + benign): B2+ flags a fault on {fired}/{n}** (every flag on a control "
          f"is a false positive); on those flags it fell back to a bare leaf name {fb}/{fired} times and "
          f"named an answer-key (fault) concept {fired - fb}/{fired} times.", ""]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--cases", default="cases/case_*")
    ap.add_argument("--project-root", type=Path, default=ROOT)
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args()
    dirs = sorted(Path(p) for p in glob.glob(str(a.project_root / a.cases))
                  if (Path(p) / "card.public.yaml").exists())
    if not dirs:
        print(f"no cases matched {a.cases}", file=sys.stderr)
        return 1
    a.out.write_text(run(dirs, a.project_root))
    print(f"wrote {a.out} ({len(dirs)} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
