#!/usr/bin/env python3
"""Validate the DECLARED B2+ knob->concept map on HELD-OUT instances (STAGE4_PLAN 4.0.6).

Builds fresh cases on DEVELOPMENT seeds (harness/seed_sets.py — never the confirmatory seeds the
sweeps run on) in a throwaway project root, then scores B2 and B2+ on each with the standard scorer.
The map was committed before this ran (sha256 recorded below and in DECISIONS); results are written
as-is to docs/audits/b2plus_validation.md — a miss is a finding, never a reason to edit the map.

Must run in the canonical container (it trains, and scoring reads hidden cards — evaluator-side):
    make docker-b2plus-validate
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from harness.baselines import B2PLUS_MAP_PATH, load_b2plus_map, score_baseline  # noqa: E402
from harness.seed_sets import CONFIRMATORY, DEVELOPMENT  # noqa: E402
from operators.registry import all_operator_ids, get_operator  # noqa: E402

CONTROL = "control.healthy.v1"
STRENGTHS = ["mild", "moderate", "severe"]
DEFAULT_SEEDS = [0, 1]
OUT = ROOT / "docs" / "audits" / "b2plus_validation.md"


def _pct(k: int, n: int) -> str:
    return f"{k}/{n}" if n else "—"


def run(seeds: list[int]) -> str:
    assert set(seeds) <= DEVELOPMENT and not set(seeds) & CONFIRMATORY, "held-out = development seeds only"
    if os.environ.get("TRAINMD_IN_CONTAINER") != "1":
        raise SystemExit("b2plus_validate: run in the canonical container (make docker-b2plus-validate)")
    from harness.build_case import build_case

    map_sha = hashlib.sha256(B2PLUS_MAP_PATH.read_bytes()).hexdigest()
    knob_map = load_b2plus_map()
    faulty = sorted(op for op in all_operator_ids() if op != CONTROL)
    design = [(op, st, sd) for op in faulty for st in STRENGTHS for sd in seeds]
    design += [(CONTROL, "mild", sd) for sd in seeds]

    rows = defaultdict(lambda: {"n": 0, "det_b2": 0, "id_b2": 0, "id_b2p": 0, "hit": 0,
                                "classes_b2": set(), "classes_b2p": set()})
    with tempfile.TemporaryDirectory(prefix="b2plus_val_") as tmp:
        tmp_root = Path(tmp)
        (tmp_root / "workloads").symlink_to(ROOT / "workloads")
        for op, st, sd in design:
            wl = getattr(get_operator(op), "WORKLOAD_FAMILY", "tabular_adult")
            case_dir = build_case(workload_name=wl, operator_id=op, strength=st, seed=sd,
                                  project_root=tmp_root)
            sub2, sc2 = score_baseline(case_dir, "b2", project_root=tmp_root)
            sub2p, sc2p = score_baseline(case_dir, "b2plus", project_root=tmp_root)
            r = rows[op]
            r["n"] += 1
            r["det_b2"] += bool(sc2["detection"]["correct"])
            r["id_b2"] += bool(sc2["identification"]["correct"])
            r["id_b2p"] += bool(sc2p["identification"]["correct"])
            r["hit"] += bool(sub2p.get("b2plus_map_hit"))
            if sub2["diagnosis"]["detected"]:
                r["classes_b2"].add(sub2["diagnosis"]["operator_class"])
                r["classes_b2p"].add(sub2p["diagnosis"]["operator_class"])
            print(f"{op} {st} seed={sd}: b2 id={sc2['identification']['correct']} "
                  f"b2+ id={sc2p['identification']['correct']} ({sub2p['diagnosis']['operator_class']})",
                  flush=True)

    tot = {k: sum(r[k] for op, r in rows.items() if op != CONTROL) for k in ("n", "id_b2", "id_b2p")}
    L = ["# B2+ validation on held-out instances (STAGE4_PLAN 4.0.6)", "",
         "> Generated by `scripts/b2plus_validate.py` (`make docker-b2plus-validate`, canonical "
         "container); do NOT hand-edit. Cases are freshly built on DEVELOPMENT seeds "
         f"{seeds} — disjoint from every confirmatory seed — so none is a sweep case.", "",
         f"- Map: `harness/b2plus_map.yaml` version {1}, sha256 `{map_sha}` — declared and "
         "committed BEFORE this ran; not tuned on these results.",
         f"- Design: {len(faulty)} faulty operators × {len(STRENGTHS)} strengths × {len(seeds)} seeds "
         f"+ control × {len(seeds)} seeds = {len(design)} cases.",
         "- Scored with the standard scorer (`harness.scoring`), exactly as an agent.", "",
         "| operator | n | B2 detection | B2 identification | B2+ identification | B2+ map hit | "
         "B2 class(es) | B2+ class(es) |",
         "|---|---|---|---|---|---|---|---|"]
    for op in sorted(rows):
        r = rows[op]
        L.append(f"| {op} | {r['n']} | {_pct(r['det_b2'], r['n'])} | {_pct(r['id_b2'], r['n'])} | "
                 f"{_pct(r['id_b2p'], r['n'])} | {_pct(r['hit'], r['n'])} | "
                 f"{', '.join(sorted(r['classes_b2'])) or '—'} | {', '.join(sorted(r['classes_b2p'])) or '—'} |")
    L += ["", f"**Faulty total:** B2 identification {_pct(tot['id_b2'], tot['n'])}, "
              f"B2+ identification {_pct(tot['id_b2p'], tot['n'])}.", "",
          "Control rows: B2 / B2+ must NOT fire (detection correct = not flagged); identification on a "
          "control is scored against the control's accepted classes.", ""]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seeds", type=int, nargs="+", default=DEFAULT_SEEDS)
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args()
    md = run(a.seeds)
    a.out.write_text(md)
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
